AgendaMVC/Controllers/AppointmentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using System.Web.Security;
using System.Net;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using AgendaMVC.Models;

namespace AgendaMVC.Controllers
{
    public class AppointmentsController : Controller

    {
        agendaEntities db = new agendaEntities();

        public ActionResult Index()
        {
            var appointment = db.appointments.Include(a => a.brokers).Include(a => a.customers);
            return View();
        }
        // GET: Appointments
        public ActionResult AddAppointment(int? id)
        {
            brokers broker = db.brokers.Find(id);
            if (id != null) { ViewBag.idBroker = new SelectList(db.brokers, "idBroker", "fullName", broker.idBroker); }
            else { ViewBag.idBroker = new SelectList(db.brokers, "idBroker", "fullName"); }
            ViewBag.idCustomer = new SelectList(db.customers, "idCustomer", "fullName");
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]

        public ActionResult AddAppointment(appointments appointment)
        {
            if (ModelState.IsValid)
                {
                bool checkDate = db.appointments.SqlQuery("SELECT * FROM appointments WHERE idBroker = '" + appointment.idBroker + "' AND dateHour BETWEEN '" + appointment.dateHour.AddMinutes(-30).ToString("yyyyMMdd HH:mm:ss") + "' AND '" + appointment.dateHour.ToString("yyyyMMdd HH:mm:ss") +"'").ToList().Any();
              
                if (checkDate)
                {
                    ModelState.AddModelError("idBroker", "Time not available.");
                    TempData["SuccessMessage"] = "Rendez-vous failed";
                }

                else
                {
                    db.appointments.Add(appointment);
                        db.SaveChanges();
                        TempData["SuccessMessage"] = "Rendez-vous enregistré avec succès";
                        return RedirectToAction("Index", "Home");
                     }
                 }
            ViewBag.idBroker = new SelectList(db.brokers, "idBroker", "fullName");
            ViewBag.idCustomer = new SelectList(db.customers, "idCustomer", "fullName");
            return View(appointment);
            
        }

        public ActionResult AppointmentList()
        {
            var appointment = db.appointments.ToList().OrderBy(x=>x.dateHour);
            return PartialView(appointment);
        }

        public ActionResult DeleteAppointment(int id)
        {
            var appointment = db.appointments.Where(model => model.idAppointment == id).First();
            db.appointments.Remove(appointment);
            db.SaveChanges();
            var list = db.appointments.ToList();
            TempData["SuccessMessage"] = "Rendez-vous supprimé";
            return RedirectToAction("Index", "Home", list);
        }

        public ActionResult ProfilAppointment(int? id)
        {
        
            appointments appointment = db.appointments.Find(id);
            if (appointment == null)
            {
                return HttpNotFound();
            }
            
            return View("_ProfilAppointment",appointment);
        }


        public ActionResult EditAppointment(int? id)
        {
            appointments appointment = db.appointments.Find(id);
            if (appointment == null)
            {
                return HttpNotFound();
            }
            ViewBag.idBroker = new SelectList(db.brokers, "idBroker", "fullName",appointment.idBroker);
            ViewBag.idCustomer = new SelectList(db.customers, "idCustomer", "fullName",appointment.idCustomer);
            return View(appointment);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditAppointment(appointments appointment)
        {

            if (ModelState.IsValid)
            {
                db.Entry(appointment).State = EntityState.Modified;
                db.SaveChanges();
                TempData["SuccessMessage"] = "Ficher rendez-vous mis à jour";
                return RedirectToAction("Index", "Home");
            }
            return View(appointment);
        }
    }
}

AgendaMVC/Controllers/BrokersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using System.Web.Security;
using System.Net;
using System.Data.Entity;
using AgendaMVC.Models;

namespace AgendaMVC.Controllers
{
    public class BrokersController : Controller
    {
        agendaEntities db = new agendaEntities();

        // GET: Brokers
        public ActionResult AddBroker()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddBroker(brokers broker)
        {
            if (ModelState.IsValid)
            {
                db.brokers.Add(broker);
                db.SaveChanges();
                TempData["SuccessMessage"] = "Courtier enregistré";
                return RedirectToAction("BrokerList");
            }
            return View(broker);

        }

        public ActionResult BrokerList()
        {
            var brokers = db.brokers.ToList();
            return View(brokers);
        }
        public ActionResult DeleteBroker(int id)
        {
            var broker = db.brokers.Where(model => model.idBroker == id).First();
            db.brokers.Remove(broker);
            db.SaveChanges();
            var list = db.brokers.ToList();
            TempData["SuccessMessage"] = "Courtier supprimé";
            return View("BrokerList", list);
        }

        public ActionResult EditBroker(int? id)
        {
            brokers broker = db.brokers.Find(id);
            if (broker == null)
            {
                return HttpNotFound();
            }
            return View(broker);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditBroker(brokers broker)
        {

            if (ModelState.IsValid)
            {
                db.Entry(broker).State = EntityState.Modified;
                db.SaveChanges();
                TempData["SuccessMessage"] = "Courtier mis à jour";
                return RedirectToAction("BrokerList");
            }
            return View(broker);
        }

        public ActionResult ProfilBroker(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var broker = db.brokers.Find(id);
            return View(broker);
        }
    }
}

AgendaMVC/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using System.Web.Security;
using System.Net;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using AgendaMVC.Models;
using PagedList;
using PagedList.Mvc;

namespace AgendaMVC.Controllers
{
    
    public class CustomersController : Controller
    {
        agendaEntities db = new agendaEntities();

        //public ActionResult Index(string search)

        //{
        //    return View(db.customers.Where(x => x.lastname == search || search == null).ToList());
        //}

        // GET: Customers
        public ActionResult AddCustomer()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddCustomer(customers customer)
        {
            var list = db.customers.ToList();
            if (ModelState.IsValid)
            {
                db.customers.Add(customer);
                db.SaveChanges();
                TempData["SuccessMessage"] = "Client enregistré";
                return RedirectToAction("CustomerList");
            }
            return View(customer);
            
        }
        public ActionResult CustomerList(string searchBy, string search, int? page)
        {
            var searchList = new List<string>() { "Nom", "Prénom", "Courriel", "Numéro de téléphone" };
            ViewBag.searchBy = new SelectList(searchList);
            var customers = db.customers.SqlQuery("select * from customers order by lastname").ToList().ToPagedList(page ?? 1, 9);

            if (searchBy == "Nom")
            {
                return View(db.customers.Where(x => x.lastname.Contains(search) || search == null).ToList().OrderBy(x => x.lastname).ToPagedList(page ?? 1, 9));
            }
            else if (searchBy == "Prénom")
            {
                return View(db.customers.Where(x => x.firstname.Contains(search) || search == null).ToList().OrderBy(x => x.lastname).ToPagedList(page ?? 1, 9));
            }
            else if (searchBy == "Courriel")
            {
                return View(db.customers.Where(x => x.mail.Contains(search) || search == null).ToList().OrderBy(x => x.lastname).ToPagedList(page ?? 1, 9));
            }
            else if (searchBy == "Numéro de téléphone")
            {
                return View(db.customers.Where(x => x.phoneNumber.Contains(search) || search == null).ToList().OrderBy(x => x.lastname).ToPagedList(page ?? 1, 9));
            }

            else if (search != null && searchBy == "Nom")
            {
                return View(customers);
            }
            //if (search != null)
            //{
            //   customers = db.customers.Where(x => x.lastname.Contains(search) || search == null).ToList().ToPagedList(page ?? 1, 7);
            //}
            return View(customers);
        }
        public ActionResult DeleteCustomer(int id)
        {
            var customer = db.customers.Where(model => model.idCustomer == id).First();
            db.customers.Remove(customer);
            db.SaveChanges();
            var list = db.customers.ToList();
            TempData["SuccessMessage"] = "Courtier supprimé";
            return View("CustomerList", list);
        }

        public ActionResult ProfilCustomer(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var customer = db.customers.Find(id);
            return View(customer);
        }
        public ActionResult EditCustomer(int? id)
        {
            customers customer = db.customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditCustomer(customers customer)
        {

            if (ModelState.IsValid)
            {
                db.Entry(customer).State = EntityState.Modified;
                db.SaveChanges();
                TempData["SuccessMessage"] = "Ficher client mis à jour";
                return RedirectToAction("CustomerList");
            }
            return View(customer);
        }
    }
}

AgendaMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <link href="~/Content/Site.css" rel="stylesheet" />
    <link href="~/Content/PagedList.css" rel="stylesheet" />
</head>
<body class="body">
    <div class="content">
        <nav class="navbar navbar-expand-lg navbar-dark fixed-top">
            <div class="container-fluid">
                <div class="float-sm-start">@Html.ActionLink("MonAgenda", "Index", "Home", new { area = "" }, new { @class = "navbar-brand ps-2 me-4" })</div>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="#">Accueil</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link active dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Ajouter aux listes</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li>@Html.ActionLink("Ajout Courtier", "AddBroker", "Brokers", new { area = "" }, new { @class = "dropdown-item" })</li>
                                <li>@Html.ActionLink("Ajout Client", "AddCustomer", "Customers", new { area = "" }, new { @class = "dropdown-item" })</li>
                                <li>@Html.ActionLink("Ajout Rendez-vous", "AddAppointment", "Appointments", new { area = "" }, new { @class = "dropdown-item" })</li>
                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link active dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Listes</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li>@Html.ActionLink("Liste courtiers", "BrokerList", "Brokers", new { area = "" }, new { @class = "dropdown-item" })</li>
                                <li>@Html.ActionLink("Liste clients", "CustomerList", "Customers", new { area = "" }, new { @class = "dropdown-item" })</li>
                            </ul>
                        </li>
                    </ul>

                </div>
            </div>
        </nav>
        <div class="container body-content">
            @RenderBody()
        </div>


    </div>
    <footer>
        
        <div>
            <p>&copy; <span class=" clock"></span> - Mon ASP.NET Application par Peter Szlachter <a class="btn-toggle"></a></p>
        </div>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
    <script src="~/Content/agenda.js"></script>
</body>
</html>